services:
  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

  main-service:
    #tty: true
    image: 100.110.100.100:5000/practice_a1-main-service:latest
    command: [
      "uvicorn", "main:app",
      "--host", "0.0.0.0", "--port", "8000",
      "--reload",
    ]
    volumes:
      - "./app:/app"
    build:
      context: ./app
    ports:
      - "8000:8000"

    #platform: linux/arm64/v8