name: Deploy FastAPI

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: debian

    steps:
      - name: Clone repository
        run: |
          git clone ${{ gitea.server_url }}/${{ gitea.repository }}.git .

      - name: Build Docker image
        run: |
          docker build \
          --platform linux/arm64 \
          -t 100.110.100.100:5000/practice:latest \
          ./app

      - name: Push Docker image
        run: |
          docker push \
          100.110.100.100:5000/practice:latest

  deploy:
    needs: build

    runs-on: debian

    steps:
      - name: Clone repository
        run: |
          git clone ${{ gitea.server_url }}/${{ gitea.repository }}.git .

      - name: Deploy
        run: |
          docker compose up -d
