name: Deploy FastAPI

on:
  push:
    branches:
      - dev/github

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
          -t 100.110.100.100:5000/practice:latest \
          ./app

      - name: Push Docker image
        run: |
          docker push \
          100.110.100.100:5000/practice:latest

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        run: |
          git clone ${{ github.server_url }}/${{ github.repository }}.git .

      - name: Deploy
        run: |
          docker compose up -d
