name: Deploy FastAPI

on:
  push:
    branches:
      - dev/github

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
          -t kalugin68/a1_github:latest \
          ./app

      - name: Push Docker image
        run: |
          docker push kalugin68/a1_github:latest

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        run: |
          git clone ${{ github.server_url }}/${{ github.repository }}.git .

      - name: Deploy
        run: |
          docker pull kalugin68/a1_github:latest
          docker compose up -d